"use client";

import React, { useState } from "react";
import Image from "next/image";
import { Cpu, Eye, ShieldCheck, ArrowRight, Layers, FileCode, CheckCircle2 } from "lucide-react";

export const ArchitectureSection = () => {
  const [activeTab, setActiveTab] = useState<"diagram" | "stages">("diagram");

  const stages = [
    {
      num: "01",
      name: "Input Ingestion & Tokenization",
      desc: "Component TSX/JSX, CSS files, API routes, or n8n workflow JSON strings are received via MCP standard input or CLI args.",
      meta: "stdio / CLI parser",
    },
    {
      num: "02",
      name: "Dual Critic Evaluation",
      desc: "UI/UX Critic evaluates aesthetic rules (contrast, 8px grid, focus rings) while Backend Guard verifies architectural integrity (secrets, rate limits, catch blocks).",
      meta: "36 Mechanical AST/Regex Checks",
    },
    {
      num: "03",
      name: "Structured Critique & Grading",
      desc: "Findings are assembled into a structured JSON envelope containing rule IDs, severities, exact line numbers, explanations, and unified diffs.",
      meta: "Deterministic AST Engine (12ms)",
    },
    {
      num: "04",
      name: "Tri-Tier Model Execution",
      desc: "Critique executes locally via MLX/GGUF fine-tuned Qwen 1.5B/7B or falls back to frontier APIs (Claude 3.5 Sonnet / GPT-4o) when configured.",
      meta: "MLX / Ollama / Anthropic",
    },
  ];

  return (
    <section id="architecture" className="border-b border-[#182430] bg-[#060a0f] py-20 lg:py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center">
          <div className="font-mono text-xs text-[#00e5ff] tracking-wider uppercase mb-2">
            SYSTEM ARCHITECTURE
          </div>
          <h2 className="font-orbitron text-2xl sm:text-4xl font-bold tracking-tight text-white uppercase max-w-3xl">
            HOW THE TWO-AGENT QUALITY GATE OPERATES
          </h2>
          <p className="mt-4 max-w-2xl font-sans text-sm sm:text-base text-[#90a4ae] leading-relaxed">
            Every file generated by your AI coding assistant is intercepted, evaluated across two specialized critic layers, and graded against 36 rule signatures.
          </p>

          {/* Tab Switcher */}
          <div className="mt-8 flex items-center border border-[#182430] bg-[#0a1017] p-1 font-mono text-xs">
            <button
              onClick={() => setActiveTab("diagram")}
              className={`px-4 py-1.5 transition-colors ${
                activeTab === "diagram"
                  ? "bg-[#182430] text-[#00e5ff] font-semibold"
                  : "text-[#90a4ae] hover:text-white"
              }`}
            >
              Visual Blueprint
            </button>
            <button
              onClick={() => setActiveTab("stages")}
              className={`px-4 py-1.5 transition-colors ${
                activeTab === "stages"
                  ? "bg-[#182430] text-[#00e5ff] font-semibold"
                  : "text-[#90a4ae] hover:text-white"
              }`}
            >
              4-Stage Pipeline Breakdown
            </button>
          </div>
        </div>

        {/* Content View */}
        {activeTab === "diagram" ? (
          <div className="mt-12 border border-[#182430] bg-[#0a1017] p-6 lg:p-10 flex flex-col items-center">
            {/* Real SVG Architectural Blueprint from Assets */}
            <div className="w-full max-w-5xl overflow-hidden relative min-h-[300px]">
              <Image
                src="/assets/architecture-diagram.svg"
                alt="Atelier Two-Agent Architecture Diagram"
                width={1200}
                height={600}
                className="w-full h-auto object-contain border border-[#182430] bg-[#060a0f]"
                unoptimized
              />
            </div>
            <div className="mt-6 flex flex-wrap items-center justify-between w-full max-w-5xl font-mono text-xs text-[#546e7a] pt-4 border-t border-[#182430]">
              <span>SCHEMATIC: ATELIER-SYS-2026</span>
              <span>INPUT: TSX / CSS / N8N JSON</span>
              <span className="text-[#00e5ff]">OUTPUT: STRUCTURED CRITIQUE + DIFF</span>
            </div>
          </div>
        ) : (
          <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 font-mono text-xs">
            {stages.map((st) => (
              <div
                key={st.num}
                className="border border-[#182430] bg-[#0a1017] p-6 flex flex-col justify-between hover:border-[#00e5ff]/50 transition-colors"
              >
                <div>
                  <div className="flex items-center justify-between text-[#546e7a] pb-3 border-b border-[#182430]">
                    <span className="font-orbitron font-bold text-[#00e5ff] text-base">{st.num}</span>
                    <span className="text-[10px]">{st.meta}</span>
                  </div>
                  <h3 className="mt-4 font-orbitron font-semibold text-white text-sm">
                    {st.name}
                  </h3>
                  <p className="mt-2 font-sans text-xs text-[#90a4ae] leading-relaxed">
                    {st.desc}
                  </p>
                </div>
                <div className="mt-6 pt-3 border-t border-[#182430] text-[#00e5ff] flex items-center gap-1">
                  <span>STAGE VERIFIED</span>
                  <CheckCircle2 className="h-3.5 w-3.5" />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
