"use client";

import React, { useState } from "react";
import Image from "next/image";
import { CheckCircle2 } from "lucide-react";

export const ArchitectureSection = () => {
  const [activeTab, setActiveTab] = useState<"diagram" | "stages">("diagram");

  const stages = [
    {
      num: "01",
      name: "Input Ingestion",
      desc: "Component TSX/JSX, CSS files, or n8n workflow JSON strings are received via MCP stdio or CLI.",
      meta: "stdio / CLI parser",
    },
    {
      num: "02",
      name: "Dual Critic Evaluation",
      desc: "UI/UX Critic evaluates aesthetic rules while Backend Guard verifies architectural soundness.",
      meta: "36 Mechanical Checks",
    },
    {
      num: "03",
      name: "Structured Grading",
      desc: "Findings are assembled into a structured JSON envelope with rule IDs, severities, and unified diffs.",
      meta: "Deterministic AST Engine (12ms)",
    },
    {
      num: "04",
      name: "Model Execution",
      desc: "Critique executes locally via MLX/GGUF fine-tuned weights or falls back to frontier APIs.",
      meta: "MLX / Ollama / Frontier",
    },
  ];

  return (
    <section id="architecture" className="py-24 bg-white dark:bg-[#090d16] border-b border-[#f1f5f9] dark:border-zinc-800 transition-colors">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center">
          <div className="text-xs font-semibold tracking-widest text-[#ff7a00] uppercase mb-3">
            SYSTEM ARCHITECTURE
          </div>
          <h2 className="font-serif text-3xl sm:text-5xl font-normal text-[#111827] dark:text-white max-w-3xl tracking-tight leading-tight">
            How the Two-Agent Quality Gate Operates
          </h2>
          <p className="mt-4 max-w-2xl font-sans text-sm sm:text-base text-[#64748b] dark:text-zinc-400 leading-relaxed">
            Every file generated by your AI coding assistant is intercepted, evaluated across two specialized critic layers, and graded against 36 rule signatures.
          </p>

          {/* Clean Pill Tab Switcher */}
          <div className="mt-8 flex items-center p-1 bg-[#f1f5f9] dark:bg-zinc-900 rounded-full text-xs font-medium border border-transparent dark:border-zinc-800">
            <button
              onClick={() => setActiveTab("diagram")}
              className={`px-6 py-2 rounded-full transition-all ${
                activeTab === "diagram"
                  ? "bg-white dark:bg-zinc-800 text-[#111827] dark:text-white shadow-sm font-semibold"
                  : "text-[#64748b] dark:text-zinc-400 hover:text-[#111827] dark:hover:text-white"
              }`}
            >
              Visual Blueprint
            </button>
            <button
              onClick={() => setActiveTab("stages")}
              className={`px-6 py-2 rounded-full transition-all ${
                activeTab === "stages"
                  ? "bg-white dark:bg-zinc-800 text-[#111827] dark:text-white shadow-sm font-semibold"
                  : "text-[#64748b] dark:text-zinc-400 hover:text-[#111827] dark:hover:text-white"
              }`}
            >
              4-Stage Pipeline
            </button>
          </div>
        </div>

        {/* View Content */}
        {activeTab === "diagram" ? (
          <div className="mt-12 rounded-3xl bg-[#fafafa] dark:bg-zinc-900/60 border border-[#e2e8f0] dark:border-zinc-800 p-6 lg:p-10 flex flex-col items-center shadow-sm">
            <div className="w-full max-w-5xl overflow-hidden relative min-h-[300px] rounded-2xl bg-white dark:bg-zinc-950 p-4 border border-[#e2e8f0] dark:border-zinc-800">
              <Image
                src="/assets/architecture-diagram.svg"
                alt="Atelier Two-Critic Pipeline Flow"
                width={1100}
                height={500}
                className="w-full h-auto object-contain rounded-xl dark:opacity-90"
              />
            </div>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-6 text-xs text-[#64748b] dark:text-zinc-400">
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-[#ff7a00]" />
                <span>UI/UX Aesthetic Layer</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-[#2563eb]" />
                <span>Backend Soundness Layer</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-[#10b981]" />
                <span>Remediation Diff Generator</span>
              </div>
            </div>
          </div>
        ) : (
          <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {stages.map((stage, idx) => (
              <div
                key={idx}
                className="p-6 rounded-3xl bg-[#fafafa] dark:bg-zinc-900 border border-[#e2e8f0] dark:border-zinc-800 flex flex-col justify-between hover:shadow-md transition-shadow"
              >
                <div>
                  <div className="font-mono text-xs font-bold text-[#ff7a00] mb-2">
                    {stage.num}
                  </div>
                  <h3 className="font-serif text-lg font-medium text-[#111827] dark:text-white mb-2">
                    {stage.name}
                  </h3>
                  <p className="font-sans text-xs text-[#64748b] dark:text-zinc-400 leading-relaxed mb-4">
                    {stage.desc}
                  </p>
                </div>
                <div className="pt-4 border-t border-[#e2e8f0] dark:border-zinc-800 text-[11px] font-mono text-[#94a3b8] dark:text-zinc-500">
                  {stage.meta}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
