"use client";

import React, { useState } from "react";
import Image from "next/image";
import { CheckCircle2 } from "lucide-react";

export const ArchitectureSection = () => {
  const [activeTab, setActiveTab] = useState<"diagram" | "stages">("diagram");

  const stages = [
    {
      num: "01",
      name: "Input Ingestion",
      desc: "Component TSX/JSX, CSS files, or n8n workflow JSON strings are received via MCP stdio or CLI.",
      meta: "stdio / CLI parser",
    },
    {
      num: "02",
      name: "Dual Critic Evaluation",
      desc: "UI/UX Critic evaluates aesthetic rules while Backend Guard verifies architectural soundness.",
      meta: "36 Mechanical Checks",
    },
    {
      num: "03",
      name: "Structured Grading",
      desc: "Findings are assembled into a structured JSON envelope with rule IDs, severities, and unified diffs.",
      meta: "Deterministic AST Engine (12ms)",
    },
    {
      num: "04",
      name: "Model Execution",
      desc: "Critique executes locally via MLX/GGUF fine-tuned weights or falls back to frontier APIs.",
      meta: "MLX / Ollama / Frontier",
    },
  ];

  return (
    <section id="architecture" className="py-24 bg-white border-b border-[#f1f5f9]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center">
          <div className="text-xs font-semibold tracking-widest text-[#ff7a00] uppercase mb-3">
            SYSTEM ARCHITECTURE
          </div>
          <h2 className="font-serif text-3xl sm:text-5xl font-normal text-[#111827] max-w-3xl tracking-tight leading-tight">
            How the Two-Agent Quality Gate Operates
          </h2>
          <p className="mt-4 max-w-2xl font-sans text-sm sm:text-base text-[#64748b] leading-relaxed">
            Every file generated by your AI coding assistant is intercepted, evaluated across two specialized critic layers, and graded against 36 rule signatures.
          </p>

          {/* Clean Pill Tab Switcher */}
          <div className="mt-8 flex items-center p-1 bg-[#f1f5f9] rounded-full text-xs font-medium">
            <button
              onClick={() => setActiveTab("diagram")}
              className={`px-6 py-2 rounded-full transition-all ${
                activeTab === "diagram"
                  ? "bg-white text-[#111827] shadow-sm font-semibold"
                  : "text-[#64748b] hover:text-[#111827]"
              }`}
            >
              Visual Blueprint
            </button>
            <button
              onClick={() => setActiveTab("stages")}
              className={`px-6 py-2 rounded-full transition-all ${
                activeTab === "stages"
                  ? "bg-white text-[#111827] shadow-sm font-semibold"
                  : "text-[#64748b] hover:text-[#111827]"
              }`}
            >
              4-Stage Pipeline
            </button>
          </div>
        </div>

        {/* View Content */}
        {activeTab === "diagram" ? (
          <div className="mt-12 rounded-3xl bg-[#fafafa] border border-[#e2e8f0] p-6 lg:p-10 flex flex-col items-center shadow-sm">
            <div className="w-full max-w-5xl overflow-hidden relative min-h-[300px] rounded-2xl bg-white p-4 border border-[#e2e8f0]">
              <Image
                src="/assets/architecture-diagram.svg"
                alt="Atelier Two-Agent Architecture Diagram"
                width={1200}
                height={600}
                className="w-full h-auto object-contain"
                unoptimized
              />
            </div>
            <div className="mt-6 flex flex-wrap items-center justify-between w-full max-w-5xl font-mono text-xs text-[#64748b] pt-4 border-t border-[#e2e8f0]">
              <span>SCHEMATIC: ATELIER-SYS-2026</span>
              <span>INPUT: TSX / CSS / N8N JSON</span>
              <span className="text-[#111827] font-semibold">OUTPUT: STRUCTURED CRITIQUE + DIFF</span>
            </div>
          </div>
        ) : (
          <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 text-xs font-sans">
            {stages.map((st) => (
              <div
                key={st.num}
                className="rounded-3xl bg-[#fafafa] border border-[#e2e8f0] p-6 flex flex-col justify-between hover:border-[#cbd5e1] hover:shadow-md transition-all"
              >
                <div>
                  <div className="flex items-center justify-between pb-3 border-b border-[#e2e8f0]">
                    <span className="font-serif font-bold text-[#ff7a00] text-xl">{st.num}</span>
                    <span className="text-[10px] font-mono text-[#64748b] uppercase">{st.meta}</span>
                  </div>
                  <h3 className="mt-4 font-semibold text-[#111827] text-base">
                    {st.name}
                  </h3>
                  <p className="mt-2 text-[#64748b] leading-relaxed">
                    {st.desc}
                  </p>
                </div>
                <div className="mt-6 pt-3 border-t border-[#e2e8f0] text-emerald-600 font-medium flex items-center gap-1.5">
                  <CheckCircle2 className="h-4 w-4" />
                  <span>Stage Verified</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
