"use client";

import React, { useState } from "react";
import { Copy, Check, Terminal, FileCode, Layers, Cpu, Compass } from "lucide-react";

interface IDEConfig {
  id: string;
  name: string;
  badge: string;
  filePath: string;
  description: string;
  configSnippet: string;
  installCommand: string;
}

const IDES: IDEConfig[] = [
  {
    id: "cursor",
    name: "Cursor IDE",
    badge: "MCP + Rules",
    filePath: "~/.cursor/mcp.json & .cursorrules",
    description: "Connect Atelier MCP server over stdio and bind cursor rules with automatic project-level overrides.",
    configSnippet: `{
  "mcpServers": {
    "atelier": {
      "command": "npx",
      "args": ["-y", "atelier-quality-gate", "serve"],
      "env": {
        "ATELIER_LLM_PROVIDER": "heuristic"
      }
    }
  }
}`,
    installCommand: "npx -y atelier-quality-gate install cursor"
  },
  {
    id: "windsurf",
    name: "Windsurf Cascade",
    badge: "Cascade Rules",
    filePath: "~/.codeium/windsurf/mcp_config.json & .windsurfrules",
    description: "Enforces continuous post-generation inspection in Codeium Cascade flows with zero latency.",
    configSnippet: `{
  "mcpServers": {
    "atelier": {
      "command": "npx",
      "args": ["-y", "atelier-quality-gate", "serve"]
    }
  }
}`,
    installCommand: "npx -y atelier-quality-gate install windsurf"
  },
  {
    id: "claude",
    name: "Claude Code / Desktop",
    badge: "Native MCP",
    filePath: "claude_desktop_config.json & CLAUDE.md",
    description: "Native Model Context Protocol integration with Claude 3.5 Sonnet / Opus CLI and desktop agent.",
    configSnippet: `{
  "mcpServers": {
    "atelier": {
      "command": "npx",
      "args": ["-y", "atelier-quality-gate", "serve"]
    }
  }
}`,
    installCommand: "npx -y atelier-quality-gate install claude"
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    badge: "Instructions",
    filePath: ".github/copilot-instructions.md",
    description: "Constrains Copilot Chat and multi-file code workspace indexing with mechanical checks.",
    configSnippet: `# GitHub Copilot Quality Gate Instructions
# Generated by Atelier (https://github.com/anshrajore/atelier-mcp)

1. Strictly obey 8px spacing harmonic scales (no arbitrary odd-pixel custom spacing).
2. Never leak plaintext credentials, JWTs, or tokens in source code.
3. Every mutation endpoint must enforce strict schema validation (Zod/Pydantic).
4. No excessive rainbow gradients or decorative clutter on interactive buttons.`,
    installCommand: "npx -y atelier-quality-gate install copilot"
  },
  {
    id: "antigravity",
    name: "Google Antigravity",
    badge: "Agent Rules",
    filePath: ".agents/rules/atelier.md",
    description: "Deep integration with Antigravity subagent loops and multi-step autonomous planning pipelines.",
    configSnippet: `{
  "mcpServers": {
    "atelier": {
      "command": "npx",
      "args": ["-y", "atelier-quality-gate", "serve"]
    }
  }
}`,
    installCommand: "npx -y atelier-quality-gate install antigravity"
  }
];

export const IDESetupMatrix = () => {
  const [activeIde, setActiveIde] = useState<IDEConfig>(IDES[0]);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const handleCopy = (key: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  return (
    <section id="ide-matrix" className="py-20 bg-white dark:bg-[#090d16] transition-colors">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950/50 border border-blue-200 dark:border-blue-800 text-[11px] font-semibold text-blue-600 dark:text-blue-400 uppercase tracking-wider mb-3">
            <Layers className="h-3.5 w-3.5" />
            <span>Universal IDE Compatibility</span>
          </div>
          <h2 className="font-serif text-3xl sm:text-4xl text-[#111827] dark:text-white">
            1-Click Setup Across Any AI Editor
          </h2>
          <p className="mt-3 font-sans text-sm text-[#4b5563] dark:text-zinc-400">
            Select your preferred development environment to copy the exact configuration or run the single automated installation command.
          </p>
        </div>

        {/* 2-Column IDE Interface */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left: IDE List (4 cols) */}
          <div className="lg:col-span-4 flex flex-col gap-2">
            {IDES.map((ide) => (
              <button
                key={ide.id}
                onClick={() => setActiveIde(ide)}
                className={`w-full text-left p-4 rounded-2xl transition-all border ${
                  activeIde.id === ide.id
                    ? "bg-white dark:bg-zinc-900 border-[#ff7a00] shadow-md dark:shadow-zinc-950/50 ring-1 ring-[#ff7a00]"
                    : "bg-[#fafafa] dark:bg-zinc-900/40 border-[#e2e8f0] dark:border-zinc-800/80 hover:bg-white dark:hover:bg-zinc-900 text-[#4b5563] dark:text-zinc-400"
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className={`font-semibold text-sm ${activeIde.id === ide.id ? "text-[#111827] dark:text-white" : ""}`}>
                    {ide.name}
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full font-mono uppercase bg-[#f1f5f9] dark:bg-zinc-800 text-[#64748b] dark:text-zinc-400">
                    {ide.badge}
                  </span>
                </div>
                <div className="text-[11px] text-[#64748b] dark:text-zinc-400 font-mono truncate">
                  {ide.filePath}
                </div>
              </button>
            ))}
          </div>

          {/* Right: Config Viewer (8 cols) */}
          <div className="lg:col-span-8 rounded-3xl bg-[#1e2330] dark:bg-zinc-950 border border-[#2d3748] dark:border-zinc-800 p-6 sm:p-8 text-white shadow-xl">
            {/* Header info */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-[#2d3748] dark:border-zinc-800">
              <div>
                <h3 className="text-lg font-serif font-medium flex items-center gap-2 text-white">
                  <span>{activeIde.name} Configuration</span>
                </h3>
                <p className="text-xs text-[#94a3b8] mt-1 font-sans">
                  {activeIde.description}
                </p>
              </div>
              <span className="text-[11px] font-mono px-3 py-1 rounded-full bg-white/10 text-zinc-300 self-start sm:self-auto">
                {activeIde.filePath}
              </span>
            </div>

            {/* Quick 1-Liner command */}
            <div className="mt-6">
              <div className="text-[11px] font-semibold text-[#ff7a00] uppercase tracking-wider mb-2 font-mono">
                1-Liner Terminal Install
              </div>
              <div className="flex items-center justify-between p-3.5 rounded-2xl bg-[#151922] dark:bg-zinc-900 border border-[#2d3748] font-mono text-xs text-gray-200">
                <div className="flex items-center gap-2 truncate">
                  <Terminal className="h-4 w-4 text-[#ff7a00] shrink-0" />
                  <span className="truncate">{activeIde.installCommand}</span>
                </div>
                <button
                  onClick={() => handleCopy("cmd-" + activeIde.id, activeIde.installCommand)}
                  className="ml-3 px-3 py-1 rounded-full bg-white/10 hover:bg-white/20 text-white text-[11px] font-sans flex items-center gap-1 transition-all shrink-0"
                >
                  {copiedKey === "cmd-" + activeIde.id ? (
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                  <span>{copiedKey === "cmd-" + activeIde.id ? "Copied" : "Copy"}</span>
                </button>
              </div>
            </div>

            {/* JSON / Ruleset Snippet */}
            <div className="mt-6">
              <div className="flex items-center justify-between text-[11px] font-semibold text-[#94a3b8] uppercase tracking-wider mb-2 font-mono">
                <span>Config File Contents</span>
                <button
                  onClick={() => handleCopy("snippet-" + activeIde.id, activeIde.configSnippet)}
                  className="hover:text-white flex items-center gap-1 text-[11px] font-sans text-[#94a3b8]"
                >
                  {copiedKey === "snippet-" + activeIde.id ? (
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                  <span>{copiedKey === "snippet-" + activeIde.id ? "Copied Snippet" : "Copy Snippet"}</span>
                </button>
              </div>
              <pre className="p-4 rounded-2xl bg-[#151922] dark:bg-zinc-900 border border-[#2d3748] text-gray-300 font-mono text-xs leading-relaxed overflow-x-auto">
                <code>{activeIde.configSnippet}</code>
              </pre>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
